### ISSUE TITLE
Errors when running on a cluster 

### ISSUE THREAD

**Issue by jianlianggao** [jianlianggao/openmole_structural_pipeline#1]
Slurm env  
```javax.script.ScriptException: gridscale.ssh.package$SFTPError: Error in sftp transfer on ssh server predict1.doc.ic.ac.uk:22
	at org.openmole.core.console.OMScripted$WrappedRequest.$anonfun$eval$1(OMScripted.scala:189)
	at org.openmole.core.console.OMScripted.withScriptContext(OMScripted.scala:87)
	at org.openmole.core.console.OMScripted$WrappedRequest.eval(OMScripted.scala:186)
	at javax.script.CompiledScript.eval(CompiledScript.java:106)
	at org.openmole.core.console.ScalaREPL.$anonfun$compile$1(ScalaREPL.scala:287)
	at org.openmole.core.project.Compiled.eval(Project.scala:102)
	at org.openmole.gui.server.core.ApiImpl.$anonfun$runScript$3(ApiImpl.scala:338)
	at org.openmole.core.outputmanager.OutputManager$.withStreamOutputs(OutputManager.scala:120)
	at org.openmole.gui.server.core.ApiImpl.$anonfun$runScript$2(ApiImpl.scala:338)
	at org.openmole.gui.server.core.ApiImpl.catchAll$1(ApiImpl.scala:331)
	at org.openmole.gui.server.core.ApiImpl.$anonfun$runScript$1(ApiImpl.scala:338)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: gridscale.ssh.package$SFTPError: Error in sftp transfer on ssh server predict1.doc.ic.ac.uk:22
	at gridscale.ssh.package$SSH.sftp(package.scala:99)
	at gridscale.ssh.package$.home(package.scala:311)
	at org.openmole.plugin.environment.ssh.package$$anon$1.home(package.scala:49)
	at org.openmole.plugin.environment.ssh.package$.sshStorageService(package.scala:84)
	at org.openmole.plugin.environment.slurm.SLURMEnvironment.storageService$lzycompute(SLURMEnvironment.scala:153)
	at org.openmole.plugin.environment.slurm.SLURMEnvironment.storageService(SLURMEnvironment.scala:152)
	at org.openmole.plugin.environment.slurm.SLURMEnvironment.<init>(SLURMEnvironment.scala:168)
	at org.openmole.plugin.environment.slurm.SLURMEnvironment$.apply(SLURMEnvironment.scala:79)
	at $line16.$read$$iw$$iw$$iw$$iw$$$$$$7c64c421a27723377c414f2e781ccfd$$$$$iw$$iw$$iw$$iw$$iw$$iw$.runOMSScript(<console>:220)
	at $line16.$read$$iw$$iw$$iw$$iw$$$$$$7c64c421a27723377c414f2e781ccfd$$$$$iw$$iw$$iw$$iw$$iw$$iw$.<init>(<console>:232)
	at $line16.$read$$iw$$iw$$iw$$iw$$$$$$7c64c421a27723377c414f2e781ccfd$$$$$iw$$iw$$iw$$iw$$iw$$iw$.<clinit>(<console>)
	at $line16.$eval$.$result$lzycompute(<console>:5)
	at $line16.$eval$.$result(<console>:5)
	at $line16.$eval.$result(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:733)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.callEither(IMain.scala:737)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.evalEither(IMain.scala:752)
	at org.openmole.core.console.OMScripted$WrappedRequest.$anonfun$evalEither$3(OMScripted.scala:168)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at scala.Console$.withIn(Console.scala:226)
	at org.openmole.core.console.OMScripted$WrappedRequest.$anonfun$evalEither$2(OMScripted.scala:168)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at scala.Console$.withErr(Console.scala:192)
	at org.openmole.core.console.OMScripted$WrappedRequest.$anonfun$evalEither$1(OMScripted.scala:167)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at scala.Console$.withOut(Console.scala:163)
	at org.openmole.core.console.OMScripted$WrappedRequest.evalEither(OMScripted.scala:166)
	at org.openmole.core.console.OMScripted$WrappedRequest.$anonfun$eval$1(OMScripted.scala:187)
	... 15 more
Caused by: net.schmizz.sshj.connection.ConnectionException: Timeout expired
	at net.schmizz.sshj.connection.ConnectionException$1.chain(ConnectionException.java:32)
	at net.schmizz.sshj.connection.ConnectionException$1.chain(ConnectionException.java:26)
	at net.schmizz.concurrent.Promise.retrieve(Promise.java:139)
	at net.schmizz.concurrent.Event.await(Event.java:105)
	at net.schmizz.sshj.connection.channel.direct.AbstractDirectChannel.open(AbstractDirectChannel.java:58)
	at net.schmizz.sshj.SSHClient.startSession(SSHClient.java:742)
	at net.schmizz.sshj.sftp.SFTPEngine.<init>(SFTPEngine.java:65)
	at net.schmizz.sshj.sftp.SFTPEngine.<init>(SFTPEngine.java:60)
	at net.schmizz.sshj.SSHClient.newSFTPClient(SSHClient.java:713)
	at gridscale.ssh.sshj.SSHClient$$anon$1.$anonfun$peerSFTPClient$1(SSHClient.scala:111)
	at scala.util.Try$.apply(Try.scala:209)
	at gridscale.ssh.sshj.SSHClient$$anon$1.wrap(SSHClient.scala:104)
	at gridscale.ssh.sshj.SSHClient$$anon$1.peerSFTPClient$lzycompute(SSHClient.scala:111)
	at gridscale.ssh.sshj.SSHClient$$anon$1.peerSFTPClient(SSHClient.scala:111)
	at gridscale.ssh.sshj.SSHClient$$anon$1.withClient(SSHClient.scala:115)
	at gridscale.ssh.sshj.SSHClient$$anon$1.canonicalize(SSHClient.scala:126)
	at gridscale.ssh.package$.$anonfun$home$1(package.scala:311)
	at gridscale.ssh.sshj.SSHClient$.sftp(SSHClient.scala:51)
	at gridscale.ssh.package$SSH.sftp(package.scala:97)
	... 46 more
Caused by: java.util.concurrent.TimeoutException: Timeout expired
	... 63 more```

**Comment by jopasserat** [comment]
fixed in https://github.com/openmole/gridscale/pull/16
